-- ============================================================================
-- UDVP Monitoring and Observability
-- Views and queries for monitoring pipeline health and performance
-- ============================================================================

USE DATABASE UDVP_DB;
USE SCHEMA UDVP_SCHEMA;
USE WAREHOUSE UDVP_WH;

-- Create monitoring view for pipeline status
CREATE OR REPLACE VIEW PIPELINE_HEALTH AS
SELECT 
    'Documents in Stage' AS METRIC,
    COUNT(*) AS VALUE,
    CURRENT_TIMESTAMP() AS MEASURED_AT
FROM DIRECTORY(@RAW_DOCUMENTS_STAGE)
UNION ALL
SELECT 
    'Parsed Documents' AS METRIC,
    COUNT(*) AS VALUE,
    CURRENT_TIMESTAMP() AS MEASURED_AT
FROM PARSED_DOCUMENTS
UNION ALL
SELECT 
    'Total Embeddings Generated' AS METRIC,
    COUNT(*) AS VALUE,
    CURRENT_TIMESTAMP() AS MEASURED_AT
FROM DOC_EMBEDDINGS
UNION ALL
SELECT 
    'Embeddings with Valid Vectors' AS METRIC,
    COUNT(*) AS VALUE,
    CURRENT_TIMESTAMP() AS MEASURED_AT
FROM DOC_EMBEDDINGS
WHERE VECTOR_EMBEDDING IS NOT NULL;

-- Create view for failed documents (documents that didn't parse)
CREATE OR REPLACE VIEW FAILED_DOCUMENTS AS
SELECT 
    d.RELATIVE_PATH AS FILE_PATH,
    d.SIZE AS FILE_SIZE_BYTES,
    d.LAST_MODIFIED,
    'Failed to parse' AS ERROR_REASON
FROM DIRECTORY(@RAW_DOCUMENTS_STAGE) d
LEFT JOIN PARSED_DOCUMENTS p ON d.RELATIVE_PATH = p.FILE_PATH
WHERE p.FILE_PATH IS NULL
    AND d.SIZE > 0;

-- Create view for processing latency
CREATE OR REPLACE VIEW PROCESSING_LATENCY AS
SELECT 
    p.FILE_PATH,
    p.DOCUMENT_ID,
    p.CLASSIFICATION,
    p.LAST_MODIFIED AS FILE_UPLOADED_AT,
    p.PROCESSED_AT AS FILE_PROCESSED_AT,
    DATEDIFF('second', p.LAST_MODIFIED, p.PROCESSED_AT) AS PARSING_LATENCY_SECONDS,
    e.EMBEDDING_GENERATED_AT,
    DATEDIFF('second', p.PROCESSED_AT, e.EMBEDDING_GENERATED_AT) AS EMBEDDING_LATENCY_SECONDS,
    DATEDIFF('second', p.LAST_MODIFIED, e.EMBEDDING_GENERATED_AT) AS TOTAL_LATENCY_SECONDS
FROM PARSED_DOCUMENTS p
JOIN DOC_EMBEDDINGS e ON p.DOCUMENT_ID = e.DOCUMENT_ID
WHERE e.CHUNK_ID = 0  -- Only look at first chunk to avoid duplicates
ORDER BY FILE_UPLOADED_AT DESC;

-- Create view for document statistics
CREATE OR REPLACE VIEW DOCUMENT_STATISTICS AS
SELECT 
    CLASSIFICATION,
    COUNT(DISTINCT DOCUMENT_ID) AS DOCUMENT_COUNT,
    COUNT(*) AS CHUNK_COUNT,
    AVG(LENGTH(TEXT_CHUNK)) AS AVG_CHUNK_LENGTH,
    SUM(LENGTH(TEXT_CHUNK)) AS TOTAL_TEXT_LENGTH
FROM DOC_EMBEDDINGS
WHERE CLASSIFICATION IS NOT NULL
GROUP BY CLASSIFICATION
ORDER BY DOCUMENT_COUNT DESC;

SELECT 'Monitoring views created successfully' AS STATUS;

-- Show current pipeline health
SELECT 'Current Pipeline Health:' AS INFO;
SELECT * FROM PIPELINE_HEALTH;

